language: node_js
node_js:
  - "0.10"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ruby
  - sudo apt-get install -qq rubygems
  - sudo gem install sass
before_script:
  - npm install -g grunt-cli